name: storybook
description: A storybook for a collection of widget.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.19.4 <=4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  digit_ui_components: 0.0.3-beta
  flutter_keyboard_visibility: ^5.4.0
  material_design_icons_flutter: ^7.0.7296
  storybook_flutter: 0.14.0
  inspector: 2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3


flutter:


  uses-material-design: true