name: digit_ui_components
description: Digit UI Design specification
version: 0.0.3-beta
homepage: https://github.com/egovernments/DIGIT-UI-LIBRARIES/tree/master/flutter/digit-ui-components

environment:
  sdk: '>=2.19.4 <=3.9.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  location: ^5.0.0
  location_platform_interface: ^3.0.0
  plugin_platform_interface: ^2.1.3
  fluttertoast: ^8.1.2
  overlay_builder: ^1.1.0
  intl: ^0.18.1
  geolocator: ^10.1.0
  collection: ^1.15.0
  file_picker: ^8.0.0+1
  flutter_dropzone: ^3.0.7





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3
  json_serializable: ^6.4.0
  bloc_test: ^9.1.0
  mockito: ^5.0.15

flutter:
  assets:
    - assets/images/
    - assets/icons/svg/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf

    - family: Roboto Italic
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf

    - family: Roboto Bold
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf

    - family: TextArea
      fonts:
        - asset: assets/fonts/TextArea.ttf