
name: Node.js Publish UI Packages

on:
  push:
    branches: [ 'develop-webpack' ]
    paths:
      - 'webpack/ui-components/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: cd webpack/ui-components/ && yarn build && npm publish --tag core-webpack-v0.1
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}